Repository f-lab-edu/MovieOn, pull requests merged in 2022-01, with the labels that each got.

#30 Add Caffeine Cache
  notification-api/notification-infrastructure/build.gradle
  notification-api/notification-infrastructure/src/main/java/kr/flab/movieon/notification/infrastructure/NotificationModuleConfiguration.java
  notification-api/notification-infrastructure/src/main/java/kr/flab/movieon/notification/infrastructure/jpa/NotificationTemplateRepositoryAdapter.java
Labels: 🏗️ADD, 🌱 Back

#37 Add Account Aggregate, Refactor Event
  account-api/account-application/src/main/java/kr/flab/movieon/account/application/AccountFacade.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/Account.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/event/RegisteredAccountConfirmEvent.java
  account-api/account-domain/src/test/java/kr/flab/movieon/account/domain/RegisterAccountConfirmProcessorTest.java
  account-api/account-infrastructure/src/main/java/kr/flab/movieon/account/infrastructure/RegisterAccountProcessorImpl.java
  account-api/account-infrastructure/src/test/java/kr/flab/movieon/account/infrastructure/RegisterAccountProcessorImplTest.java
  app/src/main/java/kr/flab/movieon/DomainEventTranslator.java
  app/src/test/java/kr/flab/movieon/security/domain/JwtTokenServiceTest.java
Labels: 🌱 Back, 🛠REFACTOR

#35 Implements PaymentCompletedEvent Send Notification.
  app/src/main/java/kr/flab/movieon/notification/integrate/AccountRepositoryAdapter.java
  notification-api/notification-domain/src/main/java/kr/flab/movieon/notification/domain/NotificationGroup.java
  notification-api/notification-domain/src/main/java/kr/flab/movieon/notification/domain/NotificationSetting.java
  notification-api/notification-domain/src/main/java/kr/flab/movieon/notification/domain/PaymentCompletedEvent.java
  notification-api/notification-infrastructure/src/main/java/kr/flab/movieon/notification/infrastructure/PaymentCompletedEventNotificationProcessor.java
  notification-api/notification-infrastructure/src/main/java/kr/flab/movieon/notification/integrate/Account.java
  notification-api/notification-infrastructure/src/main/java/kr/flab/movieon/notification/integrate/AccountRepository.java
Labels: 🏗️ADD, 🌱 Back

#40 Refactor tech debt.
  account-api/account-application/build.gradle
  account-api/account-application/src/main/java/kr/flab/movieon/account/application/AccountFacade.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/Account.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/Token.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/TokenConverter.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/TokenGenerator.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/Tokens.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/event/RegisteredAccountConfirmEvent.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/exception/AccountNotFoundException.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/exception/AccountNotVerifiedException.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/exception/InvalidEmailTokenException.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/exception/RegisterAccountConflictException.java
  account-api/account-infrastructure/src/main/java/kr/flab/movieon/account/infrastructure/AccountExceptionHandler.java
  account-api/account-presentation/src/main/java/kr/flab/movieon/account/presentation/AccountController.java
  account-api/account-presentation/src/main/java/kr/flab/movieon/account/presentation/AuthController.java
  app/src/main/java/kr/flab/movieon/integrate/security/SecurityConfig.java
  app/src/main/java/kr/flab/movieon/integrate/security/auth/JwtAuthenticationProvider.java
  app/src/main/java/kr/flab/movieon/integrate/security/domain/AccountContext.java
  app/src/main/java/kr/flab/movieon/integrate/security/domain/AccountDetailsService.java
  app/src/main/java/kr/flab/movieon/integrate/security/exception/InvalidTokenException.java
  app/src/main/java/kr/flab/movieon/integrate/security/jwt/JwtRawToken.java
  app/src/main/java/kr/flab/movieon/integrate/security/jwt/JwtToken.java
  app/src/main/java/kr/flab/movieon/integrate/security/jwt/JwtTokenConverter.java
  app/src/main/java/kr/flab/movieon/integrate/security/jwt/JwtTokenGenerator.java
  app/src/main/java/kr/flab/movieon/integrate/security/jwt/RefreshToken.java
  app/src/main/java/kr/flab/movieon/purchase/integrate/ProductRepositoryAdapter.java
  app/src/main/java/kr/flab/movieon/supports/DomainEventTranslator.java
  app/src/main/java/kr/flab/movieon/supports/GlobalExceptionHandler.java
  common/src/main/java/kr/flab/movieon/common/AccountAuthentication.java
  common/src/main/java/kr/flab/movieon/common/AuthenticatedUser.java
  common/src/main/java/kr/flab/movieon/common/Days.java
  common/src/main/java/kr/flab/movieon/common/EntityStatus.java
  common/src/main/java/kr/flab/movieon/common/Role.java
  common/src/main/java/kr/flab/movieon/common/domain/model/AbstractAggregateRoot.java
  common/src/main/java/kr/flab/movieon/common/domain/model/DomainEvent.java
  common/src/main/java/kr/flab/movieon/common/error/ErrorCode.java
  common/src/main/java/kr/flab/movieon/common/error/SystemException.java
  common/src/main/java/kr/flab/movieon/common/result/ApiResponse.java
  common/src/test/java/kr/flab/movieon/common/domain/model/AbstractAggregateRootTest.java
  notification-api/notification-domain/src/main/java/kr/flab/movieon/notification/domain/ExternalEventNotificationProcessDelegator.java
  notification-api/notification-domain/src/main/java/kr/flab/movieon/notification/domain/ExternalEventNotificationProcessor.java
  notification-api/notification-domain/src/main/java/kr/flab/movieon/notification/domain/PaymentCompletedEvent.java
  notification-api/notification-domain/src/main/java/kr/flab/movieon/notification/domain/RegisterCompletedEvent.java
  notification-api/notification-domain/src/main/java/kr/flab/movieon/notification/domain/RegisteredAccountConfirmEvent.java
  notification-api/notification-domain/src/test/java/kr/flab/movieon/notification/domain/ExternalEventNotificationProcessorTest.java
  notification-api/notification-presentation/src/main/java/kr/flab/movieon/notification/presentation/NotificationSettingApi.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/Order.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderCanceledEvent.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderCompletedEvent.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderCreatedEvent.java
  product-api/product-domain/src/main/java/kr/flab/movieon/product/domain/Product.java
  purchase-api/purchase-application/src/main/java/kr/flab/movieon/purchase/integrate/Product.java
  purchase-api/purchase-application/src/test/java/kr/flab/movieon/purchase/SpecsForPurchase.java
  purchase-api/purchase-domain/src/main/java/kr/flab/movieon/purchase/domain/Purchase.java
  purchase-api/purchase-domain/src/main/java/kr/flab/movieon/purchase/domain/PurchaseCompletedEvent.java
  purchase-api/purchase-domain/src/main/java/kr/flab/movieon/purchase/domain/PurchaseFactory.java
  purchase-api/purchase-domain/src/main/java/kr/flab/movieon/purchase/domain/PurchasedProduct.java
Labels: 🛠REFACTOR, ⛔REMOVE

#41 Refactor DRY principle
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/PasswordEncrypter.java
  account-api/account-domain/src/main/java/kr/flab/movieon/account/domain/RegisterAccountProcessor.java
  account-api/account-domain/src/test/java/kr/flab/movieon/account/domain/RegisterAccountProcessorTests.java
  account-api/account-infrastructure/src/main/java/kr/flab/movieon/account/infrastructure/PasswordEncrypterAdapter.java
  account-api/account-infrastructure/src/main/java/kr/flab/movieon/account/infrastructure/RegisterAccountProcessorImpl.java
  account-api/account-infrastructure/src/main/java/kr/flab/movieon/account/infrastructure/config/AccountModuleConfig.java
  account-api/account-infrastructure/src/main/java/kr/flab/movieon/account/infrastructure/jpa/AccountRepositoryAdapter.java
  account-api/account-infrastructure/src/main/java/kr/flab/movieon/account/infrastructure/jpa/JpaAccountRepository.java
  account-api/account-infrastructure/src/test/java/kr/flab/movieon/account/infrastructure/FakeAccountRepository.java
Labels: 🛠REFACTOR, ⛔REMOVE

#42 Implements Order Create Command
  order-api/order-application/build.gradle
  order-api/order-application/src/main/java/kr/flab/movieon/order/application/OrderCommandService.java
  order-api/order-application/src/main/java/kr/flab/movieon/order/application/empty.txt
  order-api/order-application/src/test/java/kr/flab/movieon/order/application/SpecsForCreateOrder.java
  order-api/order-application/src/test/java/kr/flab/movieon/order/domain/FakeOrderRepository.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/Customer.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/Order.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderCanceledEvent.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderCreatedEvent.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderProduct.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderValidator.java
  order-api/order-domain/src/test/java/kr/flab/movieon/order/domain/OrderTests.java
Labels: 🏗️ADD, 🌱 Back

#45 Order entity using surrogate key UUID
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/Order.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderCanceledEvent.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderCompletedEvent.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderCreatedEvent.java
Labels: 🏗️ADD, 🌱 Back

#46 Add IdGenerator
  common/src/main/java/kr/flab/movieon/common/IdGenerator.java
  common/src/test/java/kr/flab/movieon/common/IdGeneratorTest.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/Order.java
Labels: 🏗️ADD, 🌱 Back

#47 Implements OrderValidator
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/Order.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderProduct.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderValidator.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/PointManager.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/Product.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/ProductRepository.java
  order-api/order-domain/src/test/java/kr/flab/movieon/order/domain/OrderValidatorTest.java
Labels: 🏗️ADD, 🌱 Back

#48 Implements PaymentCompletedEvent in EventHandler
  order-api/order-application/src/test/java/kr/flab/movieon/order/domain/FakeOrderRepository.java
  order-api/order-domain/build.gradle
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/Customer.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/Order.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderCompletedEvent.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderProduct.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderRepository.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderValidator.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/PaymentCompletedEvent.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/PaymentCompletedProcessor.java
  order-api/order-domain/src/test/java/kr/flab/movieon/order/domain/PaymentCompletedProcessorTest.java
  order-api/order-infrastructure/build.gradle
  order-api/order-infrastructure/src/main/java/kr/flab/movieon/order/infrastructure/EventHandler.java
  order-api/order-infrastructure/src/main/java/kr/flab/movieon/order/infrastructure/empty.txt
  order-api/order-infrastructure/src/main/java/kr/flab/movieon/order/infrastructure/jpa/JpaOrderRepository.java
  order-api/order-infrastructure/src/main/java/kr/flab/movieon/order/infrastructure/jpa/OrderRepositoryAdapter.java
Labels: 🏗️ADD, 🌱 Back

#49 Implements Order Create HTTP API
  account-api/account-infrastructure/src/main/java/kr/flab/movieon/account/infrastructure/JpaAccountRepository.java
  order-api/order-application/src/main/java/kr/flab/movieon/order/application/OrderCommandService.java
  order-api/order-application/src/test/java/kr/flab/movieon/order/application/SpecsForCreateOrder.java
  order-api/order-presentation/build.gradle
  order-api/order-presentation/src/main/java/kr/flab/movieon/order/presentation/CreateOrderApi.java
  order-api/order-presentation/src/main/java/kr/flab/movieon/order/presentation/empty.txt
  order-api/order-presentation/src/test/java/kr/flab/movieon/order/presentation/CreateOrderApiTest.java
Labels: 🏗️ADD, 🌱 Back

#51 Add readme description
  Readme.md
Labels: 📰DOCS

#50 Refactor test code
  app/build.gradle
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/Customer.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/Order.java
  order-api/order-domain/src/main/java/kr/flab/movieon/order/domain/OrderProduct.java
  order-api/order-domain/src/test/java/kr/flab/movieon/order/domain/OrderValidatorTest.java
  order-api/order-domain/src/test/java/kr/flab/movieon/order/domain/PaymentCompletedProcessorTest.java
  order-api/order-presentation/src/main/java/kr/flab/movieon/order/presentation/CreateOrderApi.java
  order-api/order-presentation/src/test/java/kr/flab/movieon/order/presentation/CreateOrderApiTest.java
Labels: 🛠REFACTOR
